apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: k8s.gcr.io/ubuntu-slim:0.1
          resources:
            requests:
              cpu: 250m
              memory: 50Mi
          command: ["/bin/sh"]
          args:
          - "-c"
          - "while true; do sleep 10s; done"
